FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY wait-for-it.sh .
RUN chmod +x wait-for-it.sh

COPY . /app

EXPOSE 8080
CMD ["./wait-for-it.sh", "db:5432", "--", "uvicorn",  "main:app", "--host", "0.0.0.0", "--port", "8080"]