apiVersion: apps/v1
kind: Deployment
metadata: { name: react }
spec:
  replicas: 1
  selector: { matchLabels: { app: react } }
  template:
    metadata: { labels: { app: react } }
    spec:
      containers:
      - name: react
        # IMPORTANT: Replace with your actual image from Docker Hub
        image: yashsthr/frontend:latest
        ports: [{ containerPort: 80 }]
---
apiVersion: v1
kind: Service
metadata: { name: react }
spec:
  type: ClusterIP
  selector: { app: react }
  ports: [{ port: 80, targetPort: 80 }]